#!/usr/bin/env bash
# init.sh — Initialize a new skillbook project
# Usage: skillbook init [path]
#
# Interviews the user, creates the directory structure, and sets up
# all required files with placeholder content ready to fill in.

set -euo pipefail

TARGET="${1:-.}"

# ─── Interview ──────────────────────
echo ""
echo "═══════════════════════════════════════════"
echo "  📚 Skillbook Init"
echo "═══════════════════════════════════════════"
echo ""

read -rp "  Book slug (lowercase, hyphens, e.g. art-of-war): " SLUG
if [[ -z "$SLUG" ]]; then
  echo "  ❌ Slug is required."
  exit 1
fi
if [[ ! "$SLUG" =~ ^[a-z0-9][a-z0-9-]*[a-z0-9]$ ]]; then
  echo "  ❌ Slug must be lowercase alphanumeric with hyphens (e.g. my-book)"
  exit 1
fi

read -rp "  Title (human-readable, e.g. \"The Art of War\"): " TITLE
TITLE="${TITLE:-$SLUG}"

read -rp "  One-line description: " DESCRIPTION
DESCRIPTION="${DESCRIPTION:-A skillbook about $TITLE.}"

read -rp "  Publisher (your name/handle, e.g. brookr): " PUBLISHER
PUBLISHER="${PUBLISHER:-anonymous}"

read -rp "  Content author (original author, or press Enter if same as publisher): " CONTENT_AUTHOR
CONTENT_AUTHOR="${CONTENT_AUTHOR:-$PUBLISHER}"

read -rp "  Contact email (optional): " CONTACT
CONTACT="${CONTACT:-}"

read -rp "  License (e.g. all-rights-reserved, CC-BY-NC-4.0): " LICENSE
LICENSE="${LICENSE:-all-rights-reserved}"

read -rp "  Language code (default: en): " LANGUAGE
LANGUAGE="${LANGUAGE:-en}"

read -rp "  Suggested price, e.g. \$5.00 (default: \$5.00): " PRICE
PRICE="${PRICE:-\$5.00}"

echo ""

# ─── Create Directory ──────────────────────
BOOK_DIR="$TARGET/$SLUG"

if [[ -d "$BOOK_DIR" ]]; then
  echo "  ⚠️  Directory $BOOK_DIR already exists."
  read -rp "  Continue and overwrite root files? (y/N): " CONFIRM
  if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
    echo "  Aborted."
    exit 0
  fi
fi

mkdir -p "$BOOK_DIR/sources"
mkdir -p "$BOOK_DIR/01-foundations"

echo "  📁 Created $BOOK_DIR/"

# ─── SKILL.md ──────────────────────
# Build metadata block
METADATA_BLOCK="metadata:
  skillbook-title: \"$TITLE\"
  skillbook-author: \"$CONTENT_AUTHOR\"
  skillbook-server: \"https://skillbooks.ai\"
  skillbook-version: \"1.0.0\"
  skillbook-pages: \"0\"
  skillbook-price: \"$PRICE\""

if [[ -n "$CONTACT" ]]; then
  METADATA_BLOCK="$METADATA_BLOCK
  skillbook-contact: \"$CONTACT\""
fi

cat > "$BOOK_DIR/SKILL.md" << SKILLEOF
---
name: $SLUG
description: >-
  $DESCRIPTION
author: $PUBLISHER
license: "$LICENSE"
compatibility: "Requires HTTPS access to https://skillbooks.ai"
$METADATA_BLOCK
---

# $TITLE

$DESCRIPTION

## How to Use This Skillbook

1. Browse the Table of Contents below to find relevant sections
2. Fetch pages by constructing URLs: \`{server}/{name}/{path}\`
3. Include your API key in the \`X-Skillbook-Key\` header
4. Without a key, you'll receive a 402 response with signup info

SKILL.md and TAG-INDEX.json are always free. Content pages cost credits.

## Quick Start

<!-- PLACEHOLDER: Add 2-3 common entry points for readers -->
<!-- Example: **"What is this about?"** → \`01-foundations/00-overview.md\` -->

## Table of Contents

<!-- PLACEHOLDER: This section will be auto-generated by 'skillbook index' -->
<!-- Write your content pages first, then run: skillbook index $BOOK_DIR -->

## License

$LICENSE
SKILLEOF

echo "  ✅ SKILL.md"

# ─── README.md ──────────────────────
cat > "$BOOK_DIR/README.md" << READMEEOF
# $TITLE

$DESCRIPTION

## What's Inside

<!-- PLACEHOLDER: List the key topics and sections -->
- ...

## Why This Skillbook?

<!-- PLACEHOLDER: What makes this authoritative? What problem does it solve? -->

## At a Glance

- **Pages:** 0
- **Sections:** 0
- **License:** $LICENSE
- **Author:** $CONTENT_AUTHOR
- **Sources:** See \`sources/SOURCES.md\`
- **Last Updated:** $(date +%Y-%m-%d)
READMEEOF

echo "  ✅ README.md"

# ─── package.json ──────────────────────
# Build contact line if provided
CONTACT_LINE=""
if [[ -n "$CONTACT" ]]; then
  CONTACT_LINE="    \"contact\": \"$CONTACT\","
fi

cat > "$BOOK_DIR/package.json" << PKGEOF
{
  "name": "$SLUG",
  "version": "1.0.0",
  "description": "$DESCRIPTION",
  "author": "$PUBLISHER",
  "license": "$LICENSE",
  "keywords": [],
  "private": true,
  "devDependencies": {
    "@skillbooks/cli": "^1.0.0"
  },
  "scripts": {
    "validate": "skillbook validate .",
    "index": "skillbook index ."
  },
  "skillbook": {
    "title": "$TITLE",
    "author": "$CONTENT_AUTHOR",
${CONTACT_LINE}
    "server": "https://skillbooks.ai",
    "pages": 0,
    "price": "$PRICE",
    "language": "$LANGUAGE",
    "verified": false,
    "sources": {
      "enabled": true,
      "path": "sources/",
      "index": "sources/SOURCES.md"
    }
  }
}
PKGEOF

echo "  ✅ package.json"

# ─── sources/SOURCES.md ──────────────────────
cat > "$BOOK_DIR/sources/SOURCES.md" << SRCEOF
# Sources

<!-- List every source document used to create this skillbook. -->
<!-- Drop source files (PDF, TXT, MD, HTML) into this folder. -->

| File | Source | Date Accessed | License |
|------|--------|---------------|---------|
| <!-- example.pdf --> | <!-- Where it came from --> | <!-- $(date +%Y-%m-%d) --> | <!-- Public Domain --> |
SRCEOF

echo "  ✅ sources/SOURCES.md"

# ─── Starter section with overview ──────────────────────
cat > "$BOOK_DIR/01-foundations/00-overview.md" << OVEOF
# Foundations

<!-- PLACEHOLDER: What does this section cover? 1-2 sentences. -->

## When to Read This Section

<!-- PLACEHOLDER: What questions bring a reader here? -->
- ...

## Pages in This Section

- \`00-overview.md\` — This overview

<!-- Add pages as you create them. -->
OVEOF

echo "  ✅ 01-foundations/00-overview.md"

# ─── .gitignore ──────────────────────
cat > "$BOOK_DIR/.gitignore" << GIEOF
_build/
.verify/
node_modules/
.env*
.DS_Store
*.log
GIEOF

echo "  ✅ .gitignore"

# ─── .env.local ──────────────────────
cat > "$BOOK_DIR/.env.local" << ENVEOF
# Skillbooks API Key
# Get yours at: https://skillbooks.ai/start → "Start publishing"
# After signup, paste your key here:
SKILLBOOK_KEY=

# Optional: override the default API endpoint
# SKILLBOOK_API=https://skillbooks.ai/api
ENVEOF

echo "  ✅ .env.local"

# ─── Done ──────────────────────
echo ""
echo "═══════════════════════════════════════════"
echo "  ✅ Skillbook initialized: $BOOK_DIR/"
echo "═══════════════════════════════════════════"
echo ""
echo "  Next steps:"
echo ""
echo "  1. Drop your source material into:"
echo "     $BOOK_DIR/sources/"
echo ""
echo "  2. Update sources/SOURCES.md with what you added"
echo ""
echo "  3. Start your agent with:"
echo ""
echo "     Use the Skillbook Creator skill to build a skillbook"
echo "     from the source material in $BOOK_DIR/sources/."
echo "     The project is already initialized at $BOOK_DIR/."
echo "     Skill: https://github.com/skillbooks-ai/creator-tools/blob/main/skills/skillbook-creator/SKILL.md"
echo ""
echo "  4. When content is ready, generate the index:"
echo "     skillbook index $BOOK_DIR"
echo ""
echo "  5. Validate before publishing:"
echo "     skillbook validate $BOOK_DIR"
echo ""
